---
- hosts: all
  become: yes


  tasks:
  - name: "First test task"
    stat: 
      path: "/tmp/arun"
    register: stat_data

  - name: "Debug the vars"
    debug:
      var: stat_data

  - name: "Download the tomcat installer"
    get_url:
      url: "https://mirrors.estointernet.in/apache/tomcat/tomcat-9/v9.0.44/bin/apache-tomcat-9.0.44.tar.gz"
      dest: "/tmp/"
      mode: 0777
    register: tom_down
  
  - debug: 
      var: tom_down
  
  - name: "Unzip the downloaded tomcat"
    unarchive:
      src: /tmp/apache-tomcat-9.0.44.tar.gz
      dest: /usr/local/
      mode: 0777
      remote_src: True
